/**/*:
  ros__parameters:
    broker:
      host: 203.250.148.119
      port: 20530
    bridge:
      ros2mqtt:
        ros_topics:
        - ''
        ? ''
        : mqtt_topic: ''
          ros_type: ''
      mqtt2ros:
        mqtt_topics:
        - ''
        ? ''
        : ros_topic: ''
          ros_type: ''
